/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface MunicipioType {
  codigo_ibge: number;
  nome: string;
  uf: string;
}

export interface ClienteTemp {
  id?: string; // Generated by Supabase (UUID) or mock storage
  nome: string; // Max 150 chars
  cpf: string; // Formato 000.000.000-00 (Max 14)
  telefone: string; // Formato (00) 00000-0000 (Max 15)
  endereco: string; // Max 255 chars
  email: string; // Formato padrão @ (Max 100)
  identidade: string; // Max 20 chars (RG etc.)
  data_nascimento?: string | null; // Data de nascimento real (YYYY-MM-DD), older than today
  created_at?: string; // Date of inclusion
  municipio_codigo_ibge?: number | null;
  municipios?: {
    codigo_ibge: number;
    nome_ibge: string;
    uf: string;
  } | null;
}

export type DbMode = 'supabase' | 'demo';

export interface SupabaseConfigState {
  url: string;
  anonKey: string;
  isConfigured: boolean;
}
